
bank_logos = {
    'آینده': 'ayandeh.jpg', 'دیفالت': 'default.jpg', 'دی': 'dey.jpg', 'اقتصاد نوین': 'eghtesadnovin.jpg',
    'گردشگری': 'gardeshgari.jpg', 'ایران زمین': 'iranzamin.jpg', 'کشاورزی': 'keshavarzi.jpg', 'مسکن': 'maskan.jpg',
    'مهر': 'mehr.jpg', 'ملت': 'melat.jpg', 'ملی': 'meli.jpg', 'پارسیان': 'parsian.jpg', 'پاسارگاد': 'pasargad.jpg',
    'پست': 'postbank.jpg', 'رسالت': 'resalat.jpg', 'صادرات': 'saderat.jpg', 'سامان': 'saman.jpg', 'سرمایه': 'sarmaye.jpg',
    'سپه': 'sepah.jpg', 'شهر': 'shahr.jpg', 'سینا': 'sina.jpg', 'تجارت': 'tejarat.jpg', 'توسعه تعاون': 'tosetaaavon.jpg',
    'اقتصادنوین':'eghtesadnovin.jpg',
}
bank_websites = {
    'آینده': 'http://www.ba24.ir',
    'دیفالت': 'https://www.defaultbank.com',  
    'دی': 'http://www.bank-day.ir',
    'اقتصاد نوین': 'http://www.enbank.ir',
    'گردشگری': 'http://www.tourismbank.ir',
    'ایران زمین': 'http://www.izbank.ir',
    'کشاورزی': 'http://www.agri-bank.com/',
    'مسکن': 'http://www.bank-maskan.ir',
    'مهر': 'http://www.qmb.ir',
    'ملت': 'http://www.bankmellat.ir',
    'ملی': 'http://www.bmi.ir',
    'پارسیان': 'http://www.parsian-bank.com',
    'پاسارگاد': 'http://www.bpi.ir',
    'پست': 'http://www.postbank.ir',
    'رسالت': 'http://rqbank.ir/',
    'صادرات': 'http://www.bsi.ir',
    'سامان': 'https://www.sb24.ir',
    'سرمایه': 'http://www.sbank.ir',
    'سپه': 'http://www.banksepah.ir',
    'شهر': 'http://www.city-bank.ir',
    'سینا': 'http://www.sinabank.ir',
    'تجارت': 'http://www.tejaratbank.ir',
    'توسعه تعاون': 'http://www.ttbank.ir',
    'اقتصادنوین': 'http://www.enbank.ir',
    'توسعه صادرات': 'http://www.edbi.ir',
    'خاورمیانه': 'http://www.middleeastbank.ir',
    'رفاه کارگران': 'http://www.Refah-bank.ir',
    'صنعت و معدن': 'http://www.bim.ir',
    'کارآفرین': 'http://www.karafarinbank.com',
    'تجارتی ایران و اروپا': 'http://www.EihBank.com',
    'فیوچر بانک': 'http://www.futurebank.com.bh',
    'موسسه اعتباری کاسپین': 'http://www.caspianci.ir',
    'موسسه اعتباری توسعه': 'http://www.cid.ir',
    'موسسه اعتباری نور': 'http://noorbank.ir'
}